### ISSUE TITLE
Mismatching hashes

### ISSUE THREAD

**Issue by lukasz223968** [PALuczak/ArtificialIntelligenceFundamentals#4]
https://github.com/PALuczak/ArtificialIntelligenceFundamentals/blob/797a0a56a2448a27871d532e9f4f4398bb3ddeb3/Snake.py#L118-L123
In the reset method, float division causes the Position data_class to hold float values, which results in different hash
e.g. : `hash('X1;Y1') != hash('X1.0;Y1.0')`

instead use integer division:
`self.positions = [Position((GRID_SIDE // 2), (GRID_SIDE // 2))]`

**Comment by PALuczak** [comment]
Fixed in f0d98b4f4e2a1a5925459dc693c693599bce5f32.
